### ISSUE TITLE
not possible to set placeholder text

### ISSUE THREAD

**Issue by nerminba** [FranzSkuffka/vue-medium-editor#60] opened 2017-10-30 12:28 UTC
Placeholder is not being applied:

                mediumEditorOptions: {
                    toolbar: {buttons: ['bold', 'italic', 'strikethrough', 'anchor', 'h1', 'h2', 'h3', 'h4', 'indent', 'outdent', 'orderedlist', 'unorderedlist', 'justifyLeft', 'justifyCenter', 'justifyRight']},
                    buttonLabels: 'fontawesome',
                    mode: VueMediumEditor.MediumEditor.inlinemode,
                    maxLength: 25,
                    placeholder: {
                        text: 'Type your text',
                        hideOnClick: true
                    }
                },

this maybe connected to the previous bug I've reported. It seems that neither mode, maxLength or placeholder settings are not passed on to Medium editor.

**Comment by janwirth** [comment] 2017-10-30 21:54
Indeed. Duplicate of #59. Options are not applied _at all_.

**Closed as completed by janwirth** 2017-10-30 21:54 UTC

**Comment by nerminba** [comment] 2017-10-30 21:57
Actually I got placeHolder working so that is applied atleast.
