### ISSUE TITLE
Outdated dist folder in #1.0.4

### ISSUE THREAD

**Issue by pizzot** [FranzSkuffka/vue-medium-editor#32] opened 2017-04-21 09:33 UTC
The dist folder has not been update with the changes released with v1.0.4. Can this be fixed please?

**Comment by janwirth** [comment] 2017-04-23 17:55
Closing as duplicate of #33

**Closed as completed by janwirth** 2017-04-23 17:55 UTC
Labels: duplicate

**Comment by pizzot** [comment] 2017-04-24 09:56
This was mean to flag the issue with the particular version and the other one to think of a way to prevent the issue from happening in future.

Thanks

**Comment by janwirth** [comment] 2017-05-01 21:57
I see. Can you check #31 ? I would appreciate your perspective.

**Comment by pizzot** [comment] 2017-06-26 13:12
Sorry, was working on differnet stuff for a while. Assuming this is not relevant any more, I am having another issue: #44
