### ISSUE TITLE
Placeholder still shows after adding text with v-model

### ISSUE THREAD

**Issue by yeknava** [FranzSkuffka/vue-medium-editor#65] opened 2017-11-06 09:03 UTC
- What is the expected behavior?
0.vue loaded
1.vue-medium-editor loaded
2.adding some text to editor via v-model (like getting the latest data from server on component mounted method)
3.placeholder disappear and show text
- What is the actual behavior?
0.vue loaded
1.vue-medium-editor loaded
2.adding some text to editor via v-model (like getting the latest data from server on component mounted method)
3.placeholder exist alongside text

```example
mounted() {
    let draft = localStorage.getItem('draft');
    if(draft) {
            draft = JSON.parse(draft);
            this.$store.commit('addPost', {
                  text: draft.text,
             });
     }
 },
```

**Comment by janwirth** [comment] 2017-11-06 09:56
Closing as duplicate of #51 .

**Closed as completed by janwirth** 2017-11-06 09:56 UTC
Labels: bug, duplicate, wontfix

**Comment by yeknava** [comment] 2017-11-06 10:37
@FranzSkuffka checkout [my pull request](https://github.com/FranzSkuffka/vue-medium-editor/pull/66)
