### ISSUE TITLE
Error DOMException in v1.0.6

### ISSUE THREAD

**Issue by JeanBarriere** [FranzSkuffka/vue-medium-editor#41] opened 2017-06-09 13:21 UTC
Hi,

I currently have an issue with version `1.0.6`.
The module worked in version `1.0.4` but after update, I have the following error:
```js
Blocked a frame with origin "http://url" from accessing a cross-origin frame
```

I went back to version `1.0.4` for now.
Does anybody have a similar issue ?

Sincerely

**Comment by janwirth** [comment] 2017-06-09 14:39
Hey, are you using rawgit for the plugin? That's the source that could produce an error like that I think.

**Comment by JeanBarriere** [comment] 2017-06-09 17:20
Hi, no i use npm and the default vue-cli webpack templates to build my project

**Comment by janwirth** [comment] 2017-06-11 19:09
can you give a minimal reproduction example?

**Comment by janwirth** [comment] 2017-06-14 11:01
Did you resolve it / make any progress on this?

**Comment by janwirth** [comment] 2017-06-22 11:56
Closing as cannot reproduce.

**Closed as completed by janwirth** 2017-06-22 11:56 UTC
Labels: bug, invalid, wontfix
