### ISSUE TITLE
Ghost placeholder.

### ISSUE THREAD

**Issue by vanderlin** [FranzSkuffka/vue-medium-editor#51] opened 2017-08-14 13:34 UTC
I am getting a weird bug when I wrap the component in another component. The placeholder text is sticking around. 

![aug-14-2017 09-30-59](https://user-images.githubusercontent.com/149997/29273926-06908500-80d4-11e7-9eb4-917a3caf5cbb.gif)

when you click into the content it goes away. 

if I wrap the text with a `v-if="text"` it looks like it is fixing the bug.

**Comment by janwirth** [comment] 2017-08-14 15:59
Can you provide a more exhaustive code example? A vue component code would be enough. If you need a starting point, try the `example` branch.

**Comment by vanderlin** [comment] 2017-08-14 16:30
I think i figured out why it is happening. It was from the text being null then being set. Here is a codepen that set the :text after a second. The placeholder text is not cleared. 

https://codepen.io/vanderlin/pen/LjzegJ

**Comment by janwirth** [comment] 2017-08-14 19:09
Hey - figured this is a duplicate of #37.

I think listening for the text change is the right solution. Then detect whether it changed from `null` to something else in order to trigger the `blur` on the MediumEditor API.

You should be able to resolve this with the information I gave you. A PR would be great though :)

I will leave this open because I think it makes sense that this is fixed within vue-medium-editor although the origin is within MediumEditor.

**Comment by yeknava** [comment] 2017-11-06 10:43
@vanderlin may you check if [this patch](https://github.com/yeknava/vue-medium-editor/commit/9eb63477a06cc2df0764181d0a21703d22efd4df) will fix your issue or not ?

**Comment by janwirth** [comment] 2018-01-07 22:25
@yeknava - This patch describes the problem quite well. I would not go for such a brute-force solution though.

**Closed as completed** 2018-02-28 10:30 UTC
Labels: bug, duplicate

**Comment by janwirth** [comment] 2018-02-28 10:33
Should be fixed in 1.1.3. Please test :)
