### ISSUE TITLE
Error in event handler when creating anchor links

### ISSUE THREAD

**Issue by jackbarham** [FranzSkuffka/vue-medium-editor#50] opened 2017-08-10 18:19 UTC
When I use regular toolbar buttons it formats the text correctly without an error. However, when I use the anchor popup, load in a link then confirm I get the following error:

`[Vue warn]: Error in event handler for "edit": "TypeError: Cannot read property 'innerHTML' of undefined"`

This is the code I am using as a method:

```
processEditOperation (operation) {
	this.text = operation.event.srcElement.innerHTML
}
```

**Comment by janwirth** [comment] 2017-08-11 00:37
Can you do a minimal reproduction example?
https://github.com/FranzSkuffka/vue-medium-editor/tree/master/example

**Comment by jackbarham** [comment] 2017-08-11 11:27
I've downloaded and run your example version and the same thing happens. All the icon options work fine until I add a link, once I click the tick I get the following error:

`(unknown) Uncaught TypeError: Cannot read property 'innerHTML' of undefined`

<img width="886" alt="screen shot 2017-08-11 at 12 24 16" src="https://user-images.githubusercontent.com/1853798/29211340-6651ab68-7e90-11e7-9457-01e351839431.png">

This is a stand alone app following your setup instructions.

**Comment by janwirth** [comment] 2017-08-11 13:32
I think I know what the issue is - the events sent out by MediumEditor are corrupt.

This is a duplicate of https://github.com/yabwe/medium-editor/issues/1153

**Comment by janwirth** [comment] 2017-08-11 13:32
Side note: There is also a note on the readme: https://github.com/FranzSkuffka/vue-medium-editor#known-issues :D

**Closed as completed by janwirth** 2017-08-11 13:32 UTC

**Comment by jackbarham** [comment] 2017-08-11 13:37
Thanks, @FranzSkuffka. I'm reading through it but can't see a solution? Can you get the anchor links working?

**Comment by janwirth** [comment] 2017-08-11 13:47
So the point is that the event emitted is corrupt - we do not get the value of our contenteditable element right after the link was inserted. This means that you do not get the latest value in your model. Another editableConten event has to be triggered so that you get the latest value. Can you use this? I suggest triggering a editableContent event once a corrupt event arrived.

**Comment by jackbarham** [comment] 2017-08-11 14:51
My Javascript is fairly intermediate and not sure how the implement what you suggested. I understand this I out of scope for this plugin, do you have any code examples that could point me in right direction?

Again, thanks for you help on this.

**Comment by janwirth** [comment] 2017-08-11 15:24
I wanted to give you more but I had a call coming in right at this second :) Did not plan to leave you alone on that one.

You can use this here to trigger the `editableContent` event.
https://github.com/yabwe/medium-editor/blob/master/API.md#triggername-data-editable

```
if (operation.event.srcElement === undefined) {
  operation.event.api.elements( el => operation.event.api.trigger('editableContent', ???, el)
}
```

But I just tried this out and I can not get the result I expected.

We will have to dig through the medium editor source code.

**Comment by jackbarham** [comment] 2017-08-11 15:28
I appreciate you taking a look. Hopefully, there is an option that can be used.

**Comment by janwirth** [comment] 2017-08-11 15:36
So just a question: How high is the risk for your application? This appears to be a smaller bug to me.

COST: Link data (URL & element) is not saved
PROBABILITY: Only occurs when the user closes the document right after inserting a link.
RISK = COST x PROBABILITY

Further analysis:
By reading through the source code it seems that the data about the current editor / the element is not passed here. Can you use the `/example` to inspect?
https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L1177

**Comment by jackbarham** [comment] 2017-08-11 15:39
I'm not 100% what you mean; What exactly do you need me to inspect? 

In terms of my app, it's going to be in beta for a while so so I don't mind a few errors, but I can't get it to save the added link at all.

**Comment by janwirth** [comment] 2017-08-11 15:47
So what happens when you click 'save link' is that a few different events are triggered. The event that we listen to in the `vue-medium-editor` bridge is the `editableInput` event.

Apparently, when you click 'save link' some of the information is lost and unlike the `keyup` event it does not trigger `editableInput` with the correct data in the arguments. In the playground you might use your browser debugger to set a breakpoint on that line and check if that is the case. If so, the error should be traced back.

I will not invest any further time doing the research but if you need any hints or have any question or your app comes closer to 1.0 feel free to reach out.

**Comment by junerockwell** [comment] 2017-09-26 18:53
Hello @FranzSkuffka, I need help on this one. Everything in this issue is similar to mine. 

I just need to be able to highlight a word or words, the toolbar shows up, and paste a link. However, the error does show up and the anchor tag is not generated.

Any help or hints?

**Comment by junerockwell** [comment] 2017-09-27 22:41
I found a fix that seems to work for now. What I've noticed is that the `event` property is an empty object when we are trying to insert a link. So it makes sense that the error happens: that it could not find the `innerHtml`. 

But the `api` property is not empty and it leads to the `innerHTML` property. Below is what I've done for the `applyTextEdit()`. I've clicked all the buttons and the buttons still work along with the anchor button.
````
<template>

<medium-editor
   :text='text'
   :options="editorOpts"
   :custom-tag="div"
   v-on:edit='applyTextEdit' 
   :reuse-medium-editor-instance="false"/>

<code>{{ text }}</code>
</template>

<script>
import editor from "vue2-medium-editor";

export default {
  components: {
    'medium-editor': editor
  },
  data() {
    return {
       text: '',
       editorOpts: {
          toolbar: {
            buttons: ['bold', 'italic', 'unorderedlist','orderedlist', 'anchor'],
            diffLeft: 0,
            diffTop: -15,
          },
          placeholder: false
       }
    }
  },
  methods: {
     applyTextEdit: function (operator) {
        console.log(operator);

        this.text = operator.api.origElements.innerHTML;
     }
}
</script>

````

**Comment by janwirth** [comment] 2017-09-29 09:20
This is helpful. We should reference this in the readme.

**Comment by lopugit** [comment] 2017-10-24 05:40
Beautiful answer friend :)
