### ISSUE TITLE
NuxtJS: window is not defined

### ISSUE THREAD

**Issue by tagmetag** [FranzSkuffka/vue-medium-editor#61] opened 2017-10-31 18:19 UTC
I use it with Nuxtjs, config vender and ssr is false but get error: window is not defined. Do you know how to fix this?

**Comment by janwirth** [comment] 2017-11-01 11:57
Duplicate of https://github.com/FranzSkuffka/vue-medium-editor/issues/48

Please provide a minimum reproduction example.

vue-medium-editor itself does not use window. MediumEditor might.
https://github.com/FranzSkuffka/vue-medium-editor/search?utf8=%E2%9C%93&q=window&type=

**Comment by tagmetag** [comment] 2017-11-02 08:22
Might you develop this repository to support SSR in the future :D. I really like your repository but I use Nuxt and ca'nt install it correctly :)

**Comment by janwirth** [comment] 2017-11-02 11:06
**_Please provide a minimum reproduction example._** Please use the `/example` directory for this. Or share you project.

**Comment by janwirth** [comment] 2017-11-04 18:55
Will reopen when a minimal working example is provided.

**Closed as completed** 2018-08-24 13:54 UTC
Labels: duplicate, enhancement
